version: "3"
services:
  main:
    image: v2.1.0
    ports: ["80:80"]
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: /ecs_deploy_gh_actions/myservice
        awslogs-stream-prefix: ecs
