name: Main branch wf

on:    
  push:
    branches:
       - kp_branch
       
  
  workflow_dispatch:
  
 
jobs:
  # call test workflow   
  call-test-workflow:
     uses: ./.github/workflows/linter-test.yml

  # call the build workflow
  call-build-workflow:
    needs : call-test-workflow
    permissions: 
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    secrets: inherit
    
# call deploy to staging workflow
  call-deployStaging-workflow:
   needs: call-build-workflow
   uses: ./.github/workflows/deploy-staging.yml
   
  #call-uploadartifact-workflow:
   #needs: call-deployStaging-workflow
   #uses: ./.github/workflows/upload_to_dockerhub.yml
   #secrets: inherit
 
 # call depoly ecs workflow
  #call-deployECS-workflow:
    #permissions:
      #contents: read
      #id-token: write
    #needs : call-deployStaging-workflow
    #uses: ./.github/workflows/ecs-deploy.yml
  
  
  
   
  
