name: branch wf

on:    
  push:
    branches:
       - kp_branch 
 
jobs:
  # call test workflow   
  call-test-workflow:
     uses: ./.github/workflows/linter-test.yml

  # call the build workflow
  call-build-workflow:
    needs : call-test-workflow
    permissions: 
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    secrets: inherit
  
  
  
   
  
