name: CI 

on:      
  pull_request:
    types:
      - opened
    branches:
      - main    
  
   
jobs:  
 # call to test workflow
 # needs tag workflow to succeed
  call-test-workflow:
     if: github.event_name == 'pull_request' && github.event.action == 'opened'
     uses: ./.github/workflows/linter-test.yml
 
 # needs tests to succeed
  call-build-workflow:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    needs : call-test-workflow
    permissions: 
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    secrets: inherit
   
  # call to tag and release workflow
 # outputs : img_tag
  call-tag-workflow:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    needs: call-build-workflow
    uses: ./.github/workflows/tag.yml
    secrets: inherit
    
    
  # call to upload artifact to registry workflow
 # inputs : img_tag , as outputtes by tag workflow
  call-uploadartifact-workflow:
   if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
   needs: call-tag-workflow
   uses: ./.github/workflows/upload_to_dockerhub.yml
   with:
         "img_tag": ${{needs.call-tag-workflow.outputs.img_tag}}
   secrets: inherit
 
  
  
   
  
