name: CI 

on:
  push:
   branches:
     - main      
  pull_request:
    types:
      - opened
    branches:
      - main    
  
   
jobs:  
 # call to test workflow
 # needs tag workflow to succeed
  call-test-workflow:
     runs-on: ubuntu-latest
     if: github.event_name == 'pull_request' && github.event.action == 'opened'
     steps:
     - run: echo "i'm testing"
     #uses: ./.github/workflows/linter-test.yml
 
     
     
 
 # needs tests to succeed
  call-build-workflow:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    needs : call-test-workflow
    permissions: 
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    secrets: inherit
   
  
 
  
  
   
  
