name: "Download from jfrog"
on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          #JF_USER: ${{ secrets.JF_USER }}
          #JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          
      - name: Run JFrog CLI
        run: |
          jf rt dl  libs-snapshot-local/com/actions/demoapp/demoapp/artifacts/ --sort-by=created --sort-order=desc --limit=1
          
        
