name: Main branch wf

on:
  pull_request:
    types:
      - closed
    branches:
      - main    
  push:
    branches:
       - main
   
jobs:   
  call-test-workflow:
     uses: ./.github/workflows/linter-test.yml
     
  call-build-workflow:
    needs : call-test-workflow
    permissions: 
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    secrets: inherit
    
  call-deployStaging-workflow:
   needs: call-build-workflow
   uses: ./.github/workflows/deploy-staging.yml
   
  call-uploadartifact-workflow:
   needs: call-deployStaging-workflow
   uses: ./.github/workflows/upload_to_dockerhub.yml
   secrets: inherit
 
  
  
  
   
  
