name: save to jfrog_2
on:
   workflow_call
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to JFrog 
        uses: docker/login-action@v1
        with:
          registry: https://actions.jfrog.io/artifactory/
          username: ${{ secrets.JF_USER }}
          password: ${{ secrets.JF_PASSWORD }}
         
          
      - name: Build and push 🐳
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: https://actions.jfrog.io/artifactory/demoapp-2.0-snapshot.jar:latest
