name: "Upload to jfrog"
on: 
  workflow_dispatch:
  
jobs:
  saveartifact:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      
      #- name: try
       #docker tag img:latest myimg:1.0
      - run : | 
             mkdir -p artifacts
             docker build -t 6006012702/img:1.0 .
            
             
        
      - uses: actions/upload-artifact@v2
        with:
          name: github-actions-artifact
          path: .
          
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          #JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
          #JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
           
      - uses: actions/upload-artifact@v3
        with:
         name: Package
         path: artifacts 
      - name: Run JFrog CLI
        #Collect environment variables for the build
       # Collect VCS details from git and add them to the build
        # Publish build info
        run: |
          
          jf rt bce
          jf rt bag
          jf rt bp
          jfrog rt docker-push --url https://actions.jfrog.io/artifactory --apikey ${{secrets.JF_API_KEY}} --build-name docker-img --build-number 1.2.0 actions.jfrog.io/artifafctory/dockervirtualrepo/docker-img:d2e40a5ed58eae04750c6ecc2f3f6f0019a7981d dockervirtualrepo

