name: Bump version
on:
  #pull_request:
    #types:
      #- closed
    #branches:
      #- main
      
      workflow_call:
          outputs: 
            img_tag:
              value: ${{jobs.tag_job.outputs.img_tag}}
            
      
jobs:
  tag_job:
    runs-on: ubuntu-latest
    environment:
        name: DEV
    outputs:
      img_tag: ${{steps.tag.outputs.tag}}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'

    - id: tag
      uses: anothrNick/github-tag-action@1.61.0 # Don't use @master unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: none
        
    - run: |
          echo "img_tag = ${{steps.tag.outputs.tag}}" >> "$GITHUB_OUTPUT"

        
    - id: release
      if:  ${{steps.tag.outputs.tag }}  
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      with:
         tag_name: ${{steps.tag.outputs.tag}}
         release_name: Release ${{steps.tag.outputs.new_tag}}
         prerelease: false
    
