# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image using automated tag creation

on:
 workflow_call:
   inputs:
     img_tag:
         required: true
         type: string
 
 #workflow_dispatch:
 


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment:
       name: DEV
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        env:
         GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        with:
          images: ${{vars.DOCKER_IMAGE}}
          tags: ${{inputs.img_tag}}
           
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        env:
         GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        with:
          context: .
          push: true
          tags: ${{vars.DOCKER_IMAGE}}:${{inputs.img_tag}}
         
